app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', 'core'))
]

core/urls.py
from django.conf.urls import url

from core import views
from core.views import AuthView, ProfileView, TestListView, TestView, LogoutView, TestResultsView, StudentListView, \
    TestResultsAllView, TestEditView, ArticleListView, \
    ArticleDetailView, ArticleCreateView, ArticleEditView, ArticleDeleteView, TestCreatePlainView, AnswerListView, \
    test_search, student_search, create_test, test_search_all

urlpatterns = [
    url(r'^$', ProfileView.as_view(), name='main'),
    url(r'^auth/$', AuthView.as_view(), name='auth'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^test/(?P<pk>\d+)$', TestView.as_view(), name='test'),
    url(r'^test/all$', TestListView.as_view(), name='test_list'),


    url(r'^test/search/$', test_search_all, name='test_search_all'),
    url(r'^test/search/result/$', test_search, name='test_search'),
    url(r'^test/edit/(?P<pk>\d+)$', TestEditView.as_view(), name='test_edit'),
    url(r'^test/create/', TestCreatePlainView.as_view(), name='test_create'),

    url(r'^scores/all/$', TestResultsAllView.as_view(), name='scores_all'),
    url(r'^scores/(?P<student_id>\d+)/$', TestResultsView.as_view(), name='scores'),

    url(r'^report/$', views.print_xlsx, name='print_xlsx'),

    url(r'^student/all/$', StudentListView.as_view(), name='students_all'),
    url(r'^student/search/$', student_search, name='student_search'),

    url(r'^article/(?P<pk>\d+)/$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^article/create/$', ArticleCreateView.as_view(), name='article_create'),
    url(r'^article/edit/(?P<pk>\d+)$', ArticleEditView.as_view(), name='articles_edit'),
    url(r'^article/delete/(?P<pk>\d+)$', ArticleDeleteView.as_view(), name='article_delete'),

    url(r'^article/all/(?P<author_id>\d+)$', ArticleListView.as_view(), name='articles_by_user'),
    url(r'^article/all/$', ArticleListView.as_view(), name='articles_all'),


    url(r'^answer/list/(?P<student_id>\d+)/(?P<test_id>\d+)$', AnswerListView.as_view(), name='answer_list'),
    url(r'^answers/(?P<student_id>\d+)/(?P<test_id>\d+)$', TestResultsView.as_view(), name='answers'),



]

core/domains/question/models.py
from django.contrib.auth.models import User
from django.db import models

from core.domains.test.models import Test


class Question(models.Model):
    test = models.ForeignKey(Test, verbose_name="Тест")
    title = models.CharField("Заголовок вопроса", max_length=255)


class TextQuestion(Question):
    text = models.TextField("Текст вопроса")

    class Meta:
        verbose_name = "Текстовый вопрос"
        verbose_name_plural = "Текстовые вопросы"


class AudioQuestion(Question):
    text = models.TextField("Текст вопроса")
    audio_file = models.FileField("Аудио-файл", upload_to='audio')

    class Meta:
        verbose_name = "Аудио вопрос"
        verbose_name_plural = "Аудио вопросы"


class AnswerVariant(models.Model):
    question = models.ForeignKey(Question, verbose_name="Вопрос")
    text = models.CharField("Текст варианта", max_length=255)
    points = models.IntegerField("Количество баллов")

    class Meta:
        verbose_name = "Вариант ответа"
        verbose_name_plural = "Варианты ответа"


class Answer(models.Model):
    user = models.ForeignKey(User, verbose_name="Ученик")
    question = models.ForeignKey(Question, verbose_name="Вопрос")
    test = models.ForeignKey(Test, verbose_name="Тест")
    answer_variant = models.ForeignKey(AnswerVariant, verbose_name="Вариант ответа")

    class Meta:
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"

core/model/article/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Article(models.Model):
    user = models.ForeignKey(User, verbose_name="Автор статьи")
    publish_date = models.DateTimeField("Дата публикации", default=timezone.now)
    text = models.TextField("Текст статьи")
    title = models.CharField("Заголовок", max_length=255)

    class Meta:
        verbose_name='Статья'
        verbose_name_plural='Статьи'

core/models.py
from core.model.article.models import *
from core.model.question.models import *
from core.model.test.models import *

core/domains/article/forms.py
import json

from django.core.exceptions import PermissionDenied
from django.forms import ModelForm, Form

from core.domains.article.models import Article


class ArticleCreateForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        article = super().save(commit=False)
        article.user = self.user
        article.save()
        return article


class ArticleEditForm(Form):
    class Meta:
        model = Article
        fields = ['title', 'text']

core/domains/question/forms.py
from django.forms import ModelForm

from core.domains.question.models import Question, TextQuestion


class TextQuestionForm(ModelForm):
    class Meta:
        model = TextQuestion
        fields = ['title', 'text']

core/forms.py
from django.contrib.auth.forms import AuthenticationForm
from core.model.test.forms import *
from core.model.question.forms import *
from core.model.article.forms import *


class UserLoginForm(AuthenticationForm):
    error_messages = {
        'invalid_login': "Пожалуйста введите корректный логин и пароль"
                           "Помните, что поля зависимы от регистра",
        'inactive': "Эта учетная запись неактивна",
    }

core/model/article/forms.py
import json

from django.core.exceptions import PermissionDenied
from django.forms import ModelForm, Form

from core.model.article.models import Article


class ArticleCreateForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        article = super().save(commit=False)
        article.user = self.user
        article.save()
        return article


class ArticleEditForm(Form):
    class Meta:
        model = Article
        fields = ['title', 'text']

core/model/question/forms.py
from django.forms import ModelForm

from core.model.question.models import Question, TextQuestion


class TextQuestionForm(ModelForm):
    class Meta:
        model = TextQuestion
        fields = ['title', 'text']

core/views.py
import json
from io import BytesIO

from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.http import HttpResponseRedirect, Http404
from django.http import JsonResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic import TemplateView, RedirectView, ListView, DetailView
from django.views.generic.edit import BaseUpdateView, BaseDeleteView, FormView

from core.base import AjaxFormView
from core.model.article.models import Article
from core.model.question.gateways import AnswerGateway
from core.model.test.forms import EditTestForm
from core.model.test.gateways import UserGateway, TestGateway
from core.patterns.domains import TestDomain, QuestionDomain
from core.patterns.print import ProxyXLSPrinter

# Create your views here.


from core.model.test.models import Test, TestResult
from core.forms import UserLoginForm, ArticleCreateForm, CreateTestForm, TextQuestionForm
from core.patterns.transaction import TestTransactionScript


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profile/index.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['user'] = self.request.user

        return context

class AuthView(FormView):
    http_method_names = ['get', 'post']
    form_class = UserLoginForm
    template_name = 'auth/index.html'
    success_url = '/'

    def form_valid(self, form):
        login(self.request, form.get_user())
        redirect_url = self.request.GET.get('next')

        if redirect_url:
            return HttpResponseRedirect(redirect_url)

        return super(AuthView, self).form_valid(form)

    def form_invalid(self, form):
        return super(AuthView, self).form_invalid(form)

class TestCreatePlainView(LoginRequiredMixin, AjaxFormView):
    template_name = 'test/test_create.html'
    form_class = CreateTestForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs['user'] = self.request.user
        return kwargs

class LogoutView(RedirectView):
    url = '/'
    http_method_names = ['get', 'post']

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        return super(LogoutView, self).get_redirect_url(*args, **kwargs)


class TestListView(LoginRequiredMixin, ListView):
    model = Test
    template_name = 'test/test_list.html'


class TestResultsAllView(LoginRequiredMixin, ListView):
    model = TestResult
    template_name = 'test/test_result_all.html'

class TestEditView(LoginRequiredMixin, AjaxFormView):
    template_name = 'test/test_edit.html'
    form_class = EditTestForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs['user'] = self.request.user
        kwargs['test_instance'] = Test.objects.get(pk=self.kwargs.get('pk'))
        return kwargs

class TestResultsView(LoginRequiredMixin, ListView):
    model = TestResult
    template_name = 'test/test_result_list.html'

    def get_queryset(self):
        student = User.objects.get(pk=self.kwargs.get('student_id'))
        return TestResult.objects.filter(user=student).all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student'] = User.objects.get(pk=self.kwargs.get('student_id'))
        return context


class AnswerListView(LoginRequiredMixin, TemplateView):

    template_name = 'answer/answers.html'

    def get_context_data(self, **kwargs):
        answers_list = AnswerGateway.get_answers(self.kwargs.get('student_id'), self.kwargs.get('test_id'))
        context = super().get_context_data(**kwargs)
        context['answer_list'] = answers_list
        return context


class TestView(LoginRequiredMixin, DetailView):
    model = Test
    template_name = 'test/test.html'


@login_required()
def test_search(request):
    if request.method == 'POST':
        test = Test.objects.filter(title=request.POST.get('query_text')).first()
        test_results = TestResult.objects.filter(test=test).all()
        return render_to_response('test/test_result_all.html', {'testresult_list': test_results},
                                  context_instance=RequestContext(request))
    elif request.method == 'GET':
        test_results = TestResult.objects.all()
        return render_to_response('test/test_result_all.html', {'testresult_list': test_results},
                                  context_instance=RequestContext(request))

@login_required()
def test_search_all(request):
    if request.method == 'POST':
        if request.POST.get('title'):
            tests = Test.objects.filter(title=request.POST.get('title')).all()
        else:
            tests = Test.objects.all()
        return render_to_response('test/test_list.html', {'test_list': tests},
                                  context_instance=RequestContext(request))
    elif request.method == 'GET':
        tests = Test.objects.all()
        return render_to_response('test/test_list.html', {'test_list': tests},
                                  context_instance=RequestContext(request))

@login_required()
def student_search(request):
    if request.method == 'POST':
        if request.POST.get('username'):
            users = UserGateway.get_students_by_name(username=request.POST.get('username'))
        else:
            users = UserGateway.get_all_students()
        return render_to_response('student/student_list.html', {'user_list': users},
                                  context_instance=RequestContext(request))
    elif request.method == 'GET':
        users = UserGateway.get_all_students()
        return render_to_response('student/student_list.html', {'user_list': users},
                                  context_instance=RequestContext(request))

class StudentListView(TemplateView):
    template_name = 'student/student_list.html'

    def get_context_data(self, **kwargs):
        user_list = UserGateway.get_all_students()
        context = super().get_context_data(**kwargs)
        context['user_list'] = user_list
        return context



@login_required()
def create_test(request,):
    test = {}
    questions = {}
    errors = {}

    if request.method == "POST":
        data = request.POST.get('data')
        if data:
            data = json.loads(data)
            data_test = data.get("test", {})
            data_test['user'] = request.user.id
            errors['test'] = TestDomain().create_test(data_test)

            questions = data.get("questions", {})
            if questions:
                for question_id, form in questions.items():
                    errors['question'] = QuestionDomain().create_question(form)

            if errors:
                return JsonResponse({'status': 'FAILED', 'message': errors })

            return JsonResponse({'status': 'OK'})
    elif request.method == "GET":
        return render_to_response('test/test_create.html', {
            'question_0': TextQuestionForm(),
            'question_hidden': TextQuestionForm(),
        }, context_instance=RequestContext(request))

@login_required()
def update_test(request):
    test = {}
    questions = {}

    if request.method == "POST":
        data = request.POST.get('data')
        if data:
            data = json.loads(data)
            data_test = data.get("test", {})
            data_test['user'] = request.user.id
            errors = TestTransactionScript().change_test(data_test)

            if errors:
                return JsonResponse({'status': 'FAILED', 'message': errors })

            return JsonResponse({'status': 'OK'})
    elif request.method == "GET":

        return render_to_response('test/test_edit.html', {
            'test': TestGateway.get_test_by_id(request.GET.get("test_id")),
            'question_0': TextQuestionForm(),
            'question_hidden': TextQuestionForm(),
        }, context_instance=RequestContext(request))


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article/article_details.html'


class ArticleCreateView(LoginRequiredMixin, AjaxFormView):
    form_class = ArticleCreateForm
    template_name = 'article/article_create.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs['user'] = self.request.user
        return kwargs


class ArticleEditView(LoginRequiredMixin, AjaxFormView, BaseUpdateView):
    model = Article
    fields = ['title', 'text']
    template_name = 'article/article_edit.html'



class ArticleDeleteView(LoginRequiredMixin, AjaxFormView, BaseDeleteView):
    success_url = '/'
    model = Article

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()

        if self.object.user == self.request.user or self.request.user.is_superuser:
            self.object.delete()
            return JsonResponse({'status': 'OK'})
        else:
            raise Http404('Article not exist')


class ArticleListView(ListView):
    model = Article
    template_name = 'article/article_list.html'

    def get_queryset(self):
        if self.kwargs.get('author_id'):
            user= User.objects.get(pk=self.kwargs.get('author_id'))
            self.template_name = 'article/article_list_edit.html'
            return Article.objects.filter(user=user).all()
        else:
            return Article.objects.all()


@login_required
def print_xlsx(request):
    output = BytesIO()
    printer = ProxyXLSPrinter()
    output = printer.print(output)
    output.seek(0)
    response = HttpResponse(output.read(), content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    response['Content-Disposition'] = "attachment; filename=report.xlsx"

    return response

core/templates/article/article_create.html
{% extends 'layout/main.html' %}

{% block content %}
    <div class="container">
        <h2>Создание статьи</h2>
        <form class="row test-edit" method="post" action="{% url 'core:article_create'  %}" id="article">
            {% csrf_token %}
            <div class="form__line">
                <label for="id_title">Название</label>
                <input type="text" name="title"  id="id_title" class="js-input">
                <div class="error hidden" id="error_title">
                    <p class="js-error-text error__text"></p>
                </div>
            </div>

            <div class="form__line">
                <label for="id_desc">Текст</label>
                <textarea name="text" id="id_desc" class="u-full-width test-edit__text-area js-input" ></textarea>
                <div class="error hidden" id="error_text">
                    <p class="js-error-text error__text"></p>
                </div>
            </div>

            <input class="button button-primary test-edit__save" type="submit" value="Добавить">
        </form>

        <div class="message_success hidden">
            <h3>Успех!</h3>
            <p>Статья успешно создана.</p>
            <p><a href="{% url 'core:articles_by_user' request.user.id %}" class="button button-primary">К списку статей</a>
            </p>
        </div>
    </div>
{% endblock %}

{% block requirejsconfig %}
    {% include 'components/js.html' with name='article' %}
{% endblock %}

core/templates/article/article_details.html
{% extends 'layout/main.html' %}

{% block content %}
    <div class="container">
        <h2>{{ article.title }}</h2>
        <p>{{ article.publish_date }}</p>
        <p>{{ article.text }}</p>


         <a href="{% url 'core:articles_all' %}" class="button button-primary"> К списку статей</a>
    </div>

{% endblock %}

core/templates/article/article_edit.html
{% extends 'layout/main.html' %}

{% block content %}
    <div class="container">
        <h2>Редактирование статьи</h2>
        <form class="row test-edit" method="post" action="{% url 'core:articles_edit' article.id %}" id="article">
            {% csrf_token %}
            <div class="form__line">
                <label for="id_title">Название</label>
                <input type="text" name="title" value="{{ article.title }}" id="id_title" class="js-input">
                <div class="error hidden" id="error_title">
                    <p class="js-error-text error__text"></p>
                </div>
            </div>

            <div class="form__line">
                <label for="id_desc">Текст</label>
                <textarea name="text" id="id_desc" class="js-input u-full-width test-edit__text-area">{{ article.text }}</textarea>
                <div class="error hidden" id="error_text">
                    <p class="js-error-text error__text"></p>
                </div>
            </div>

            <input class="button button-primary test-edit__save" type="submit" value="Сохранить">
            <a class="button test-edit__delete js-delete" href="{% url 'core:article_delete' article.id %}">Удалить</a>
        </form>

        <div class="message_success hidden">
            <h3>Успех!</h3>
            <p>Статья успешно сохранена.</p>
            <p><a href="{% url 'core:articles_by_user' request.user.id %}" class="button button-primary">К списку статей</a>
            </p>
        </div>
        <div class="message_success-delete hidden">
            <h3>Успех!</h3>
            <p>Статья успешно удалена.</p>
            <p><a href="{% url 'core:articles_by_user' request.user.id %}" class="button button-primary">К списку статей</a>
            </p>
        </div>
    </div>
{% endblock %}

{% block requirejsconfig %}
    {% include 'components/js.html' with name='article' %}
{% endblock %}

core/templates/article/article_list.html
{% extends 'layout/main.html' %}

{% block content %}

    <div class="container">
        <div class="search">
            <form action="{% url 'core:student_search' %}" method="post">
                <input type="text" placeholder="Введите название статьи" class="u-full-width" name="title">
                <div class="icon-wrapper">
                    <i class="icon_search"></i>
                </div>
                <button type="submit" class="button-primary">
                    Искать
                </button>
            </form>
        </div>

        <table class="test-table u-full-width">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Автор</th>
                    <th>Дата создания</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for article in article_list %}
                    <tr>
                        <td>{{ article.title }}</td>
                        <td>{{ article.user }}</td>
                        <td>{{ article.publish_date }}</td>
                        <td><a href="{% url 'core:article_detail'  article.id %}">Посмотреть</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

core/templates/article/article_list_edit.html
{% extends 'layout/main.html' %}

{% block content %}

    <div class="container">
        <div class="search">
            <form action="{% url 'core:student_search' %}" method="post">
                <input type="text" placeholder="Введите название статьи" class="u-full-width" name="title">
                <div class="icon-wrapper">
                    <i class="icon_search"></i>
                </div>
                <button type="submit" class="button-primary">
                    Искать
                </button>
            </form>
        </div>
        <div class="actions_test">
                <div class="actions__item action_item-add">
                    <i class="icon_action icon_plus"></i>
                    <a href="{% url 'core:article_create' %}" class="link_create">Создать статью</a>
                </div>
        </div>
        <table class="test-table u-full-width">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Дата создания</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for article in article_list %}
                    <tr>
                        <td>{{ article.title }}</td>
                        <td>{{ article.publish_date }}</td>
                        <td><a href="{% url 'core:articles_edit' article.id %}">Редактировать</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}